/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_categories"];
        put?: never;
        post: operations["post_categories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_category"];
        put?: never;
        post?: never;
        delete: operations["delete_category"];
        options?: never;
        head?: never;
        patch: operations["patch_category"];
        trace?: never;
    };
    "/categories/{categoryId}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_nodes"];
        put?: never;
        post: operations["post_nodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{categoryId}/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_node"];
        put: operations["put_node"];
        post?: never;
        delete: operations["delete_node"];
        options?: never;
        head?: never;
        patch: operations["patch_node"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mqtt/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_topics"];
        put?: never;
        post: operations["post_topics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_topic"];
        put?: never;
        post?: never;
        delete: operations["delete_topic"];
        options?: never;
        head?: never;
        patch: operations["patch_topic"];
        trace?: never;
    };
    "/topics/{topicId}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_values"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/values/{valueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_value"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_ws"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Categories */
        CategoriesDto: {
            categories: components["schemas"]["CategoryDto"][];
        };
        /** Category */
        CategoryDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** CreateCategory */
        CreateCategoryDto: {
            name: string;
        };
        /** CreateNode */
        CreateNodeDto: {
            name: string;
            /** Format: uuid */
            topicId: string;
        };
        /** CreateTopic */
        CreateTopicDto: {
            mqttTopic: string;
            name?: string | null;
        };
        /** Health */
        HealthDto: {
            status: string;
        };
        /** ModifyCategory */
        ModifyCategoryDto: {
            name?: string | null;
        };
        /** ModifyNode */
        ModifyNodeDto: {
            name?: string | null;
            /** Format: uuid */
            topicId?: string | null;
        };
        /**
         * ModifyTopic
         * @description Optional name field! If the name field is omitted, the existing name remains unchanged. If the name field is explicitly null, the name is cleared (unset). If a string value is provided, the name is updated to that value.
         */
        ModifyTopicDto: {
            mqttTopic?: string | null;
            name?: string | null;
        };
        /** MqttStatus */
        MqttStatusDto: {
            connected: boolean;
        };
        /** Node */
        NodeDto: {
            /** Format: uuid */
            categoryId: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            topicId: string;
        };
        /** Nodes */
        NodesDto: {
            nodes: components["schemas"]["NodeDto"][];
        };
        /** Topic */
        TopicDto: {
            /** Format: uuid */
            id: string;
            mqttTopic: string;
            name?: string | null;
        };
        /** Topics */
        TopicsDto: {
            topics: components["schemas"]["TopicDto"][];
        };
        /** Value */
        ValueDto: {
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            topicId: string;
            value: string;
        };
        /** Values */
        ValuesDto: {
            values: components["schemas"]["ValueDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        categories: components["schemas"]["CategoryDto"][];
                    };
                };
            };
        };
    };
    post_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Creates a new category and returns it */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                    };
                };
            };
        };
    };
    get_category: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                    };
                };
            };
        };
    };
    delete_category: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletes the category */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_category: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string | null;
                };
            };
        };
        responses: {
            /** @description Modifies the category and returns it */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                    };
                };
            };
        };
    };
    get_nodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of nodes in a category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        nodes: components["schemas"]["NodeDto"][];
                    };
                };
            };
        };
    };
    post_nodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: uuid */
                    topicId: string;
                };
            };
        };
        responses: {
            /** @description Creates a new node and returns it */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        categoryId: string;
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        topicId: string;
                    };
                };
            };
        };
    };
    get_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                categoryId: string;
                /** @description Node id */
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the node */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        categoryId: string;
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        topicId: string;
                    };
                };
            };
        };
    };
    put_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                categoryId: string;
                /** @description Node id */
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    categoryId: string;
                };
            };
        };
        responses: {
            /** @description Moves the node to a new category and returns it */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        categoryId: string;
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        topicId: string;
                    };
                };
            };
        };
    };
    delete_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                categoryId: string;
                /** @description Node id */
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletes the node */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                categoryId: string;
                /** @description Node id */
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string | null;
                    /** Format: uuid */
                    topicId?: string | null;
                };
            };
        };
        responses: {
            /** @description Modifies the node and returns it */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        categoryId: string;
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        topicId: string;
                    };
                };
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the health of the service */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the status of the MQTT connection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        connected: boolean;
                    };
                };
            };
        };
    };
    get_topics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of topics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        topics: components["schemas"]["TopicDto"][];
                    };
                };
            };
        };
    };
    post_topics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    mqttTopic: string;
                    name?: string | null;
                };
            };
        };
        responses: {
            /** @description Creates a new topic and returns it */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        mqttTopic: string;
                        name?: string | null;
                    };
                };
            };
        };
    };
    get_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Topic id */
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the topic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        mqttTopic: string;
                        name?: string | null;
                    };
                };
            };
        };
    };
    delete_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Topic id */
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletes the topic */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Topic id */
                topicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    mqttTopic?: string | null;
                    name?: string | null;
                };
            };
        };
        responses: {
            /** @description Modifies the topic and returns it */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        mqttTopic: string;
                        name?: string | null;
                    };
                };
            };
        };
    };
    get_values: {
        parameters: {
            query?: {
                /** @description Limit of values to return. Minimum = 1, Maximum = 500 and Default = 100. */
                limit?: number;
                /** @description Get values before this value. If neither before nor after are provided, the latest values are returned. If both before and after are provided, before takes precedence. */
                before?: string;
                /** @description Get values after this value. */
                after?: string;
            };
            header?: never;
            path: {
                /** @description Topic id */
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of values in a topic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        values: components["schemas"]["ValueDto"][];
                    };
                };
            };
        };
    };
    get_value: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Topic id */
                topicId: string;
                /** @description Value id */
                valueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the value */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        topicId: string;
                        value: string;
                    };
                };
            };
        };
    };
    get_ws: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upgrade to a WebSocket connection */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
